FROM openjdk:17
EXPOSE 8080

# Copiez le fichier JAR de l'application dans le conteneur
ADD target/jenkinsDemo.jar /jenkinsDemo.jar

# Commande pour exécuter l'application Spring Boot
ENTRYPOINT ["java", "-jar", "/jenkinsDemo.jar"]